version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  checkout_code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            curl -LO https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
            unzip terraform_1.0.9_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
      - run:
          name: Terraform Init
          command: terraform init
      - persist_to_workspace:
          root: .
          paths:
            - "*"
            - ".terraform/*"
            - ".terraform.lock.hcl"
  apply:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - terraform/apply:
          path: .
      - persist_to_workspace:
          root: .
          paths:
            - "*"
            - ".terraform/*"
            - ".terraform.lock.hcl"

  destroy:
    executor: terraform/default
    steps:
      - attach_workspace:
          at: .
      - terraform/destroy:
          path: .


workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - checkout_code
      - approval-plan:
          type: approval
          filters:
            branches:
              only: main
      - terraform/plan:
          pre-steps:
            - attach_workspace:
                at: .
          requires:
            - approval-plan
            - checkout_code
          filters:
            branches:
              only: main
      - apply:
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
      - approval-destroy:
          type: approval
          filters:
            branches:
              only: main
      - destroy:
          requires:
            - approval-destroy
            - apply
          filters:
            branches:
              only: main
