version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  checkout_code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - checkout_code
      - approval-plan:
          type: approval
          requires:
            - checkout_code
          filters:
            branches:
              only: main
      - terraform/plan:
          requires:
            - approval-plan
            - checkout_code
          filters:
            branches:
              only: main
      - approval-destroy:
          type: approval
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
      - terraform/apply:
          requires:
            - terraform/plan
            - checkout_code
          filters:
            branches:
              only: main
      - terraform/destroy:
          requires:
            - approval-destroy
            - terraform/apply
          filters:
            branches:
              only: main
