version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  checkout_code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - "*"

workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - checkout_code
      - approval-plan:
          type: approval
          requires:
            - checkout_code
          filters:
            branches:
              only: main
      - terraform/plan:
          requires:
            - approval-plan
          filters:
            branches:
              only: main
          pre-steps:  # These steps run before the orb's steps
            - attach_workspace:
                at: .
      - approval-destroy:
          type: approval
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
      - terraform/apply:
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
          pre-steps:
            - attach_workspace:
                at: .
      - terraform/destroy:
          requires:
            - approval-destroy
            - terraform/apply
          filters:
            branches:
              only: main
          pre-steps:
            - attach_workspace:
                at: .
