version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1

jobs:
  checkout_code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace: # This saves job artifacts to be used by downstream jobs
          root: . # This specifies the directory to save (current directory)
          paths: # Specify the directories and files to save
            - "*"

workflows:
  version: 2
  deploy-infrastructure:
    jobs:
      - checkout_code
      - approval-plan:
          type: approval
          requires:
            - checkout_code
          filters:
            branches:
              only: main
      - terraform/plan:
          requires:
            - approval-plan
          filters:
            branches:
              only: main
          steps:
            - attach_workspace: # This step retrieves data saved in the previous job
                at: . # The directory where the data should be loaded
      - approval-destroy:
          type: approval
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
      - terraform/apply:
          requires:
            - terraform/plan
          filters:
            branches:
              only: main
          steps:
            - attach_workspace:
                at: .
      - terraform/destroy:
          requires:
            - approval-destroy
            - terraform/apply
          filters:
            branches:
              only: main
          steps:
            - attach_workspace:
                at: .
