version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: Build Job
          command: echo "Running build job!"

workflows:
  version: 2
  main_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
